import type { Metadata } from "next";
import "./globals.css";
import Header from "@/ui/Header";
import Navigation from "@/ui/Navigation";
import { useEffect } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: { icon: './favicon.ico' }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <Navigation></Navigation>
        <Header></Header>
        <main className="relative overflow-auto md:w-[calc(100%-90px)] md:float-right z-0">
          {children}
          <div className='w-full h-[75px] md:hidden block md:h-[100vh] md:w-[90px] bg-transparent'></div>
        </main>
      </body>
    </html>
  );
}
